  - name: copy config files
    template: src=ceph.conf dest=/etc/ceph/ceph.conf

  - name: disk-clean
    command: ceph-disk zap {{ item }}
    with_items:
               - /dev/vdb
               - /dev/vdc
               - /dev/vdd
  #             - /dev/vde
  #             - /dev/vdf
  #             - /dev/vdg

  - name: prepare
    command: ceph-disk prepare --cluster {{ clustername }} --cluster-uuid {{ fsid }} --fs-type xfs {{ item }} /dev/vdb
    with_items:
               - /dev/vdc
               - /dev/vdd
  #             - /dev/vde
  #             - /dev/vdf
  #             - /dev/vdg  

  - name: active
    command: ceph-disk activate {{ item }}
    with_items:
               - /dev/vdc1
               - /dev/vdd1
  #             - /dev/vde1
  #             - /dev/vdf1
  #             - /dev/vdg1    
    tags:
      - active-ceph-osd 
