---
#- name: copy ceph.conf
#  template: src=ceph.conf dest=/etc/ceph/ceph.conf

#- name: create admin user
#  shell: radosgw-admin user create --uid=admin --display-name="admin user" && radosgw-admin caps add --uid=admin --caps="users=*;buckets=*;metadata=*;usage=*;zone=*"

- name: install apache2 cgi
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - libapache2-mod-fastcgi
    - openssl
    - ssl-cert  
    - libcrypto++-dev    

- name: restart apache2 service
  service: name=apache2 state=restarted

- name: load rewrite fastcgi ssl mode
  shell: sudo a2enmod rewrite && sudo a2enmod fastcgi && sudo a2enmod ssl && sudo a2enmod headers && sudo a2ensite rgw.conf && sudo a2dissite 000-default.conf

- name: mkdir ssl directory
  file: path=/etc/apache2/ssl state=directory

#这个是交互是的暂时需要手动执行
- name: create apache.crt
  shell: sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/apache2/ssl/apache.key -out /etc/apache2/ssl/apache.crt

- name: copy rgw.conf s3gw.fcg
  template: src={{ item.src }} dest={{ item.dest }}
  with_items:
    - { src: 'rgw.conf', dest: '/etc/apache2/sites-available/rgw.conf' }
    - { src: 's3gw.fcgi', dest: '/var/www/s3gw.fcgi' }

- name: to fcgi privileges
  shell: chown www-data:www-data /var/www/s3gw.fcgi && chmod +x /var/www/s3gw.fcgi

- name: restart apache2 service
  service: name=apache2 state=restarted
