#- name: create uuid
#  local_action: script /etc/ansible/jinyc/ceph-ansible-auto/roles/add-ceph-mon/handlers/initcephconf.sh

#- name: create initial config file
#  local_action: template src=templates/ceph.conf dest=/etc/ansible/jinyc/ceph-ansible-auto/roles/{{ item }}/files
#  with_items: 
#             -  add-ceph-mon 
#             -  add-ceph-osd 

- name: copy configuration
  template: src=ceph.conf dest=/etc/ceph/ceph.conf

- name: create mon directory
  file: path=/var/lib/ceph/mon/{{ clustername }}-{{ ansible_hostname }}  state=directory owner=ceph group=ceph mode=755

- name: mon initial
  command: ceph-mon --cluster {{ clustername }} --setuser ceph --setgroup ceph --mkfs -i {{ ansible_hostname }} --fsid {{ fsid }}

- name: autostart mon flag
  file: path=/var/lib/ceph/mon/{{ clustername }}-{{ ansible_hostname }}/{{ item }} state=touch owner=ceph group=ceph mode=644
  with_items:
             - done
             - upstart

- name: start mon deamon
  command: start ceph-mon id={{ ansible_hostname }} 
