---
- name: install libnss3-tools on debian
  package:
    name: libnss3-tools
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: create nss directory for keystone certificates
  file:
    path: "{{ radosgw_nss_db_path }}"
    state: directory
    owner: root
    group: root
    mode: 0644

